include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    always_put_required_named_parameters_first: true
    avoid_relative_lib_imports: true
    unawaited_futures: true
    unrelated_type_equality_checks: true
    empty_catches: true

analyzer:
  exclude:
    # Codegen
    - "lib/**.gen.dart"
    - "lib/**.g.dart"
    - "lib/**.gr.dart"
    - "lib/**.gm.dart"
    - "lib/**.freezed.dart"
    - "lib/**.config.dart"
    - "**/generated_plugin_registrant.dart"
    # Build
    - "build/**"
    # Tests
    - "test/**.mocks.dart"
    - ".test_coverage.dart"
    # Packages
    - "packages/**"
    # Assets
    - "assets/**"
    # Localization
    - "lib/src/config/localization/generated/**"
